variables:
  BUILD_DIR: '/var/www/builds'
  BUILD_HOST: 't2.ertelecom.ru'
  SHARED_DIR_BASE: '/var/shared'
  FPM_IMAGE: 'dhub.ertelecom.ru/zhakov/php:5.4-fpm'
  MEMCACHE_IMAGE: 'memcached:1.4'
  MONGO_IMAGE: 'mongo:3.1'

before_script:
  - export PROJECT_NAME=`basename $CI_PROJECT_DIR|sed s/\\\./-/`
  - export PROJECT_GROUP=`echo $CI_PROJECT_DIR | awk -F'/' '{print $(NF-1)}' | tr 'A-Z' 'a-z'`
  - export TEST_URL=${CI_BUILD_REF_NAME}.${PROJECT_NAME}.${PROJECT_GROUP}.${BUILD_HOST}
  - export PROJECT_DIR_SUFFIX=${PROJECT_GROUP}/${PROJECT_NAME}/${CI_BUILD_REF_NAME}
  - export SHARED_DIR=${SHARED_DIR_BASE}/${PROJECT_GROUP}/${PROJECT_NAME}/${CI_BUILD_REF_NAME}
  - export PROJECT_DIR=${BUILD_DIR}/${PROJECT_GROUP}/${PROJECT_NAME}/${CI_BUILD_REF_NAME}
  - export CONTAINER_PRJ="`echo ${PROJECT_GROUP}${PROJECT_NAME}${CI_BUILD_REF_NAME}|sed 's/-//g'`"
  - export NGINX_PROJECT_DIR=${PROJECT_DIR}/data
  - env

stages:
  - build

Deploy to fpm:
  type: build
  script:
    - mkdir -p ${SHARED_DIR}
    - mkdir -p ${PROJECT_DIR} # create project ref build
    - sudo rsync -ra --exclude .git . ${PROJECT_DIR}/   #sync project ref
    - ssh-keyscan -p 10022 gitlab.ertelecom.ru > ~/.ssh/known_hosts
    - cd ${PROJECT_DIR}
    - mkdir -p ${PROJECT_DIR}/config
    - envsubst < contrib/docker-compose/docker-compose.tmpl > ${PROJECT_DIR}/config/docker-compose.yml
    - cd ${PROJECT_DIR}/config/
    - sudo docker-compose -p ${CONTAINER_PRJ} up -d
    - export WEB1_EXPOSE_PORT=`sudo docker inspect --format='{{(index (index .NetworkSettings.Ports "9000/tcp") 0).HostPort}}' ${CONTAINER_PRJ}_web1_1`
    - export request_filename=\$request_filename #envsubst eats my variable. that cant be changed. http://stackoverflow.com/questions/2914220/
    - export upstream_addr=\$upstream_addr #envsubst eats my variable. that cant be changed. http://stackoverflow.com/questions/2914220/
    - envsubst < ${PROJECT_DIR}/contrib/nginx/site.tmpl > ${PROJECT_DIR}/config/site.cfg

    - docker exec ${CONTAINER_PRJ}_web1_1 composer global require "fxp/composer-asset-plugin:~1.1.1"
    - docker exec ${CONTAINER_PRJ}_web1_1 composer install --working-dir protected
    
    - cd ${PROJECT_DIR}
    - sudo chmod 777 -R data/assets
    - sudo chmod 777 -R protected/runtime
    - sudo mkdir -p /var/log/services/nginx/${PROJECT_DIR_SUFFIX}/
    - sudo systemctl restart nginx || sudo journalctl -xn
    - env
  only:
    - master
    - /^web-.*$/
  tags:
    - fpm.testing
